# =======================================
# ===============注册中心配置==============
# =======================================
# 注册中心配置

#客户端配置

#    serviceUrl:
#      defaultZone: http://XXXXX/eureka/
#  instance:
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#日志级别配置，不同环境不一致
logging:
  level:
    org:
      springframework:
        #Spring框架日志级别
        web: debug
#模拟服务所在网关路由/nginx配置
server:
  context-path: /debuggerking
#数据库配置
spring:
  http:
    #文件上传大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 部署运行命令
#    nohup java -server -Xmx512M -Xms512M -XX:NewRatio=2 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=58084 -jar XXX.jar &
