#应用配置
app:
  name: www.power-web.com

#日志系统配置
logging:
  config: classpath:logback-spring.xml

#服务部署端口
server:
  port: 8099
#Spring配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    check-template-location: false
  #服务部署名
  application:
    name: service-power-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  profiles:
#    #当前环境
#    active: dev

# 部署运行命令
#    nohup java -server -Xmx512M -Xms512M -XX:NewRatio=2 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=58084 -jar XXX.jar &
