authorization:
  user-profile:
    key: Authorization
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.202:8761/eureka/,http://192.168.2.203:8760/eureka/
jasypt:
  encryptor:
    password: ''
logging:
  level:
    com:
      ovfintech:
        ctemplate:
          mapper: debug
spring:
  datasource:
    connection-test-query: select 1
    driverClassName: com.mysql.jdbc.Driver
    password: ''
    url: ''
    username: ''
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
