#应用配置
app:
  name: www.caofanCPU.com

#注册中心配置
eureka:
  client:
    registryFetchIntervalSeconds: 5
  instance:
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 5
#文件访问系统配置
file:
  url: http://SERVICE-FILE
#日志系统配置
logging:
  config: classpath:logback-spring.xml
#Mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.xyz.caofancpu.model
#资源路径键名配置
resource_access_key: DEBUGGER_RESOURCE
#网关内部队列配置
ribbon:
  ServerListRefreshInterval: 2000
#服务部署端口
server:
  port: 8098
#Spring配置
spring:
  #服务部署名
  application:
    name: service-debuggerking
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    #当前环境
    active: dev
#自定义卡夫卡主题
test:
  spring:
    kafka:
      topics: caofanCPU,demo
#用户中心服务配置
user-profile-url: http://USER-SERVICE

swagger:
  authPathRegex: ^(?!auth).*$
  showApi: true
  authorizationKey: Authorization
