authorization:
  user-profile:
    key: Authorization
eureka:
  client:
    serviceUrl:
      defaultZone: ''
jasypt:
  encryptor:
    password: ''
logging:
  level:
    com:
      ovfintech:
        ctemplate:
          mapper: debug
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: ''
    url: ''
    username: ''
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
