# =======================================
# ===============注册中心配置==============
# =======================================
# 注册中心配置

#客户端配置
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#    serviceUrl:
#      defaultZone: http://XXXXX/eureka/
#  instance:
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#日志级别配置，不同环境不一致
logging:
  level:
    com:
      xyz:
        caofancpu:
          #DTO数据库操作日志级别
          mapper: debug
    org:
      springframework:
        #Spring框架日志级别
        web: debug
#模拟服务所在网关路由/nginx配置
server:
  context-path: /debuggerking
#数据库配置
spring:
  datasource:
    connection-test-query: select 1
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.150:3306/bynz_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: ENC(7q5tQ5gmPhEE7o+aAaDnVg==)
jasypt:
  encryptor:
    password: e!JdljyJ^e4I5oU
  http:
    #文件上传大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #Kafka配置
  kafka:
    #Kafka消息中心访问URL
    bootstrap-servers: 192.168.2.203:9092
    #Kafka客户端组名配置
    consumer:
      group-id: caofanGroup

# 部署运行命令
#    nohup java -server -Xmx512M -Xms512M -XX:NewRatio=2 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=58084 -jar XXX.jar &
