####---------------------------------
####-----------  分块配置  -----------
####---------------------------------





####---------------------------------
####--------- 数据库密码加密  ---------
####---------------------------------
#jasypt:
#    encryptor:
#        password: e!JdljyJ^e4I5oU


####---------------------------------
####------------ 服务配置 ------------
####---------------------------------
server:
  # 端口
  port: 8090
  # 路由
  context-path: /scalaBoot



####---------------------------------
####------------ 核心配置 ------------
####---------------------------------
spring:
  application:
    # 服务名称
    name: SCALA_BOOT
  # 数据源配置
  datasource:
    # 数据库驱动
    driverClassName: com.mysql.jdbc.Driver
    # 检测数据库连接
    connection-test-query: select 1
    # 数据库连接
    url: jdbc:mysql://127.0.0.1:3306/debuggerking?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    # 登录名
    username: root
    # 加密后的密码
    password: ENC(KX8h5m7elpf72DmySlXGaA==)
